DriveTank:
  slowHeight: 40
  slowScaler: 0.5
  maxAcceleration: 12.0
  maxAccelerationSlow: 2.0
  slowerHeight: 60
  slowerScaler: 0.3
  maxAccelerationSlower: 1.0
  modifiers: { deadzone: 0.1, exponent: 2.0 }
LiftContinuous:
  sliderTolerance: 2
  sliderThreshold: 1
PickerPick:
  rollerPower: -0.8
  cubeDetectDistance: 200
  cubeInDistance: 50
  cubeCloseDistance: 200
  sampler: { period: .1 }
  t1: .5
  t2: .15
  t3: .55
^DriveRotate: { rotationSpeed: 180, maxAcceleration: 400 }
^DrivePath: { speed: 100, arcSpeed: 60, radius: 30, maxAcceleration: 120 }
$PickerPick:
  - PivotPick
  - { class: Wait, period: 1 }
  - PickerPick
  - PivotHome
#$PickerPickTo45:
#  - PivotPick
#  - { class: Wait, period: 2.0 }
#  - PickerPick
#  - { class: PivotToAngle, angle: 135.0 }
^PickerRelease:
  time: 1.0
  minDropAngle: 160.0
  drop: false
PickerRelease:
  rollerPower: 1.0
  time: 1.0
  drop: false
PivotFlip:
  forwardAngle: 180.0
  pivotPoint: 90.0
  backwardAngle: 0.0
$PickerRelease:
  - PickerRelease
  - PivotHome
$PickerDrop:
  - { class: PickerRelease, rollerPower: 0.2, time: 1.0, drop: true }
  - PivotHome
PivotHome:
  { class: PivotToAngle, angle: 0.0 }
PivotPick:
  { class: PivotToAngle, angle: 180.0 }
PivotRelease:
  { class: PivotToAngle, angle: 180.0 }
LiftHome:
  { class: LiftToHeight, height: 0.0 }
LiftSwitch:
  { class: LiftToHeight, height: 23.0 }
LiftScaleLow:
  { class: LiftToHeight, height: 64.0 }
LiftScaleHigh:
  { class: LiftToHeight, height: 80.0 }
LiftForClimb:
  { class: LiftToHeight, height: 72.0 }

$LiftScaleLowTele:
  - PivotRelease
  - LiftScaleLow

$LiftScaleHighTele:
  - PivotRelease
  - LiftScaleHigh

DriveStraightTest:
  { class: DriveStraight, speed: 40.0, endSpeed: 0.0, maxAcceleration: 20.0, distance: 240.0}
DriveRotateTest:
  { class: DriveRotate, angle: 90.0 }


$TestAuto:
  - { class: DriveStraight, speed: 60.0, endSpeed: 0.0, angle: 0.0, maxAcceleration: 40.0, distance: 240.0 }
  - { class: DriveRotate, angle: 180.0 }
  - { class: DriveStraight, speed: 60.0, endSpeed: 0.0, angle: 180.0, maxAcceleration: 40.0, distance: 180.0 }
  - { class: DriveRotate, angle: 90.0 }
  - { class: DriveStraight, angle: 80.0, speed: 60.0, endSpeed: 0.0, maxAcceleration: 40.0, distance: 100.0 }

$UpAndOut:
  - LiftSwitch
  - { class: Wait, period: 0.5 }
  - PivotRelease

$LiftHomeWithDelay:
  - { class: Wait, period: .75 }
  - LiftHome

$CenterLSwitchAuto:
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, angle: 0.0, maxAcceleration: 60.0, distance: 24.0 }
  - { class: DriveRotate, angle: -30.0 }
  - { name: $UpAndOut, parallel: true }
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, distance: 76.0, maxAcceleration: 60.0 }
  - { name: PickerRelease, parallel: true }
  - { name: $LiftHomeWithDelay, parallel: true }
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, maxAcceleration: 60.0, distance: -76.0 }
  - { class: DriveRotate, angle: 5.0, rotationSpeed: 270.0 }
  - { name: PickerPick, parallel: true }
  - { class: DriveStraight, speed: 40.0, endSpeed: 0.0, maxAcceleration: 60.0, distance: 42.0 }
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, maxAcceleration: 60.0, distance: -42.0 }
  - { class: DriveRotate, angle: -35.0 }
  - LiftSwitch
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, distance: 76.0, maxAcceleration: 60.0 }
  - PickerRelease

$LogAuto:
  - { class: Log, message: "~ERROR: NO AUTO SEQUENCE SELECTED" }

StartLeftPose:
  class: SetPose
  x: -100
  y: 19
  yaw: -90

$TestDrive:
  - StartLeftPose
  - class: DrivePath
    reverse: true
    speed: 120
    parallel: true
    maxAcceleration: 120.0
    path:
      - { x: -100, y: 19 }
      - { x: -100, y: 162, speed: 60, arcSpeed: 60, radius: 48 }
      - { x: -88, y: 268 }
  - { class: WaitForPath, remainingDistance: 4.0 }
  - PrintPose

LiftClimb:
  power: -1
  time: 1



#
#
#     Autonomous Sequences
#
#

Scale:
  { class: AutoSelector, type: STARTING_POSITION, left: $ScaleStartLeft, right: $ScaleStartRight }

$ScaleStartLeft:
  - { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: $AutoStartLeftScaleLeft, R: $AutoStartLeftScaleRight }

$AutoStartLeftScaleLeft:
  - StartLeftPose
  - class: DrivePath
    reverse: true
    speed: 120
    parallel: true
    maxAcceleration: 120.0
    path:
      - { x: -100, y: 19 }
      - { x: -100, y: 162, speed: 60, arcSpeed: 60, radius: 48 }
      - { x: -88, y: 268 }
  - { class: WaitForPath, remainingDistance: 4.0 }
  - PrintPose

$ScaleStartRight:
  - { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: $AutoStartRightScaleLeft, R: $AutoStartRightScaleRight }

Switch:
  { class: AutoSelector, type: STARTING_POSITION, center: $SwitchStartCenter }

$SwitchStartCenter:
  - { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $AutoSwitchLeft, R: $AutoSwitchRight }