DriveTank:
  slowHeight: 40
  slowScaler: 0.5
  maxAcceleration: 12.0
  maxAccelerationSlow: 2.0
  slowerHeight: 60
  slowerScaler: 0.3
  maxAccelerationSlower: 1.0
  modifiers: { deadzone: 0.1, exponent: 2.0 }
LiftContinuous:
  sliderTolerance: 2
  sliderThreshold: 1
PickerPick:
  rollerPower: -0.8
  cubeDetectDistance: 200
  cubeInDistance: 50
  cubeCloseDistance: 200
  sampler: { period: .1 }
  t1: .5
  t2: .15
  t3: .55
AutoPick:
  class: PickerPick
  rollerPower: -0.8
  cubeDetectDistance: 260
  cubeInDistance: 50
  cubeCloseDistance: 260
  sampler: { period: .1 }
  t1: .5
  t2: .15
  t3: .55
^DriveRotate: { rotationSpeed: 180, maxAcceleration: 400 }
^DrivePath: { speed: 100, arcSpeed: 60, radius: 30, maxAcceleration: 120 }
$PickerPick:
  - PivotPick
  - WaitForAngle
  - PickerPick
  - PickerHold
  - PivotHome
$AutoPick:
  - PivotPick
  - WaitForAngle
  - AutoPick
  - PickerHold
  - PivotHome
#$PickerPickTo45:
#  - PivotPick
#  - { class: Wait, period: 2.0 }
#  - PickerPick
#  - { class: PivotToAngle, angle: 135.0 }
^PickerRelease:
  time: 1.0
  minDropAngle: 160.0
  drop: false
PickerRelease:
  rollerPower: 1.0
  time: 1.0
  drop: false
PivotFlip:
  forwardAngle: 180.0
  pivotPoint: 90.0
  backwardAngle: 0.0
$PickerRelease:
  - PickerRelease
  - PivotHome
$PickerDrop:
  - { class: PickerRelease, rollerPower: 0.2, time: 1.0, drop: true }
  - PivotHome
PivotHome:
  { class: PivotToAngle, angle: 0.0 }
PivotPick:
  { class: PivotToAngle, angle: 180.0 }
PivotRelease:
  { class: PivotToAngle, angle: 180.0 }
LiftHome:
  { class: LiftToHeight, height: 0.0 }
LiftSwitch:
  { class: LiftToHeight, height: 23.0 }
LiftScaleLow:
  { class: LiftToHeight, height: 64.0 }
LiftScaleHigh:
  { class: LiftToHeight, height: 80.0 }
LiftForClimb:
  { class: LiftToHeight, height: 72.0 }

$LiftScaleLowTele:
  - PivotRelease
  - LiftScaleLow

$LiftScaleHighTele:
  - PivotRelease
  - LiftScaleHigh

DriveStraightTest:
  { class: DriveStraight, speed: 40.0, endSpeed: 0.0, maxAcceleration: 20.0, distance: 240.0}
DriveRotateTest:
  { class: DriveRotate, angle: 90.0 }


$TestAuto:
  - { class: DriveStraight, speed: 60.0, endSpeed: 0.0, angle: 0.0, maxAcceleration: 40.0, distance: 240.0 }
  - { class: DriveRotate, angle: 180.0 }
  - { class: DriveStraight, speed: 60.0, endSpeed: 0.0, angle: 180.0, maxAcceleration: 40.0, distance: 180.0 }
  - { class: DriveRotate, angle: 90.0 }
  - { class: DriveStraight, angle: 80.0, speed: 60.0, endSpeed: 0.0, maxAcceleration: 40.0, distance: 100.0 }

$UpAndOut:
  - LiftSwitch
  - WaitForHeight
  - PivotRelease

$LiftHomeWithDelay:
  - { class: Wait, period: .75 }
  - LiftHome

$AutoSwitchLeft:
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, angle: 0.0, maxAcceleration: 75.0, distance: 24.0 }
  - { class: DriveRotate, angle: -30.0 }
  - { name: $UpAndOut, parallel: true }
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, distance: 80.0, maxAcceleration: 75.0 }
  - PickerRelease
  - { name: $LiftHomeWithDelay, parallel: true }
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, maxAcceleration: 75.0, distance: -76.0 }
  - { class: DriveRotate, angle: 5.0, rotationSpeed: 270.0 }
  - { name: PickerPick, parallel: true }
  - { class: DriveStraight, speed: 40.0, endSpeed: 0.0, maxAcceleration: 75.0, distance: 42.0 }
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, maxAcceleration: 75.0, distance: -42.0 }
  - { class: DriveRotate, angle: -35.0 }
  - LiftSwitch
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, distance: 80.0, maxAcceleration: 75.0 }
  - PickerRelease
  - LiftHome

$AutoSwitchRight:
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, angle: 0.0, maxAcceleration: 75.0, distance: 24.0 }
  - { class: DriveRotate, angle: 25.0 }
  - { name: $UpAndOut, parallel: true }
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, distance: 80.0, maxAcceleration: 75.0 }
  - PickerRelease
  - { name: $LiftHomeWithDelay, parallel: true }
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, maxAcceleration: 75.0, distance: -76.0 }
  - { class: DriveRotate, angle: 0.0, rotationSpeed: 270.0 }
  - { name: PickerPick, parallel: true }
  - { class: DriveStraight, speed: 40.0, endSpeed: 0.0, maxAcceleration: 75.0, distance: 42.0 }
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, maxAcceleration: 75.0, distance: -42.0 }
  - { class: DriveRotate, angle: 25.0 }
  - LiftSwitch
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, distance: 80.0, maxAcceleration: 75.0 }
  - PickerRelease
  - PivotHome
  - LiftHome
  - { class: DriveStraight, speed: 80.0, endSpeed: 0.0, distance: -10.0, maxAcceleration: 75.0 }

$LogAuto:
  - { class: Log, message: "~ERROR: NO AUTO SEQUENCE SELECTED" }

StartLeftPose:
  class: SetPose
  x: -109
  y: 19
  yaw: -90

StartRightPose:
  class: SetPose
  x: 109
  y: 19
  yaw: -90

LiftClimb:
  power: -1
  time: 1
  stopHeight: 6

PickerHold:
  power: -0.2

#
#
#     Autonomous Sequences
#
#

Scale:
  { class: AutoSelector, type: STARTING_POSITION, left: $ScaleStartLeft, right: $ScaleStartRight }

$ScaleStartLeft:
  - { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: $AutoStartLeftScaleLeft, R: $AutoStartLeftScaleRight }

$AutoStartLeftScaleLeft:
  - StartLeftPose
  - { class: PickerHold, power: -0.3 }
#  - LiftSwitch
  - class: DrivePath
    reverse: true
    speed: 90
    parallel: true
    maxAcceleration: 50.0
    path:
      - { x: -109, y: 19 }
      - { x: -109, y: 168, arcSpeed: 90, radius: 256 }
      - { x: -84, y: 280 }
  - { class: WaitForPath, remainingDistance: 36.0 }
  - LiftScaleHigh
  - { class: WaitForPath, remainingDistance: 1.0 }
  - WaitForHeight
  - PickerRelease
  - LiftHome
  - WaitForHeight
  - { parallel: true, name: $AutoPick }
  - class: DrivePath
    speed: 40
    maxAcceleration: 50.0
    path:
      - { x: -84, y: 280 }
      - { x: -73, y: 232, radius: 10, arcSpeed: 20 }
  - WaitForCube
  - class: DrivePath
    speed: 50
    parallel: true
    reverse: true
    maxAcceleration: 50.0
    path:
      - { x: -73, y: 232 }
      - { x: -84, y: 256, radius: 14, arcSpeed: 50 }
      - { x: -80, y: 280 }
  - WaitForAngle
  - LiftScaleHigh
  - WaitForHeight
  - PickerRelease
  - LiftHome
  - WaitForHeight

$AutoStartLeftScaleRight:
  - StartLeftPose
  - PickerHold
  - class: DrivePath
    parallel: true
    reverse: true
    speed: 100
    maxAcceleration: 70.0
    path:
      - { x: -109, y: 19 }
      - { x: -109, y: 79 }
      - { x: -109, y: 234, radius: 48 }
      - { x: 0, y: 234, speed: 50 }
      - { x: 80, y: 234, radius: 32, arcSpeed: 40, speed: 40 }
      - { x: 85.5, y: 266 }
      - { x: 85.5, y: 280 }
  - { class: WaitForPath, remainingDistance: 100.0 }
  - LiftScaleHigh
  - { class: WaitForPath, remainingDistance: 2.0 }
  - WaitForHeight
  - PickerRelease
  - LiftHome
  - WaitForHeight
  - { parallel: true, name: $AutoPick }
  - class: DrivePath
    speed: 40
    maxAcceleration: 50.0
    path:
      - { x: 85.5, y: 272 }
      - { x: 73, y: 228, radius: 10, arcSpeed: 20 }
  - WaitForCube


$ScaleStartRight:
  - { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: $AutoStartRightScaleLeft, R: $AutoStartRightScaleRight }

$AutoStartRightScaleLeft:
  - StartRightPose
  - PickerHold
  - class: DrivePath
    parallel: true
    reverse: true
    speed: 100
    maxAcceleration: 70.0
    path:
      - { x: 109, y: 19 }
      - { x: 109, y: 79 }
      - { x: 109, y: 234, radius: 48 }
      - { x: 0, y: 234, speed: 70 }
      - { x: -80, y: 234, radius: 32, arcSpeed: 40, speed: 40 }
      - { x: -85.5, y: 266 }
      - { x: -85.5, y: 280 }
  - { class: WaitForPath, remainingDistance: 100.0 }
  - LiftScaleHigh
  - { class: WaitForPath, remainingDistance: 2.0 }
  - WaitForHeight
  - PickerRelease
  - LiftHome
  - { parallel: true, name: $AutoPick }
  - class: DrivePath
    speed: 40
    maxAcceleration: 50.0
    path:
      - { x: -85.5, y: 280 }
      - { x: -73, y: 232, radius: 10, arcSpeed: 20 }
  - WaitForCube

$AutoStartRightScaleRight:
  - StartRightPose
  - { class: PickerHold, power: -0.3 }
#  - LiftSwitch
  - class: DrivePath
    reverse: true
    speed: 80
    parallel: true
    maxAcceleration: 50.0
    path:
      - { x: 109, y: 19 }
      - { x: 109, y: 162, arcSpeed: 80, radius: 256 }
      - { x: 84, y: 272 }
  - { class: WaitForPath, remainingDistance: 36.0 }
  - LiftScaleHigh
  - { class: WaitForPath, remainingDistance: 1.0 }
  - WaitForHeight
  - PickerRelease
  - LiftHome
  - WaitForHeight
  - { parallel: true, name: $AutoPick }
  - class: DrivePath
    speed: 40
    maxAcceleration: 50.0
    path:
      - { x: 84, y: 272 }
      - { x: 73, y: 224, radius: 10, arcSpeed: 20 }
  - WaitForCube
  - class: DrivePath
    speed: 50
    parallel: true
    reverse: true
    maxAcceleration: 50.0
    path:
      - { x: 73, y: 224 }
      - { x: 84, y: 248, radius: 6, arcSpeed: 50 }
      - { x: 80, y: 272 }
  - WaitForAngle
  - LiftScaleHigh
  - WaitForHeight
  - PickerRelease
  - LiftHome
  - WaitForHeight

Switch:
  { class: AutoSelector, type: STARTING_POSITION, center: $SwitchStartCenter }

$SwitchStartCenter:
  - { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $AutoSwitchLeft, R: $AutoSwitchRight }

$HoldPowerTestAuto:
  - { class: PickerHold, power: 0.3 }



# 1 cube frozen autos
# todo reduce speeds, accel

$AutoStartLeftScaleLeft1Cube:
  - StartLeftPose
  - { class: PickerHold, power: -0.3 }
#  - LiftSwitch
  - class: DrivePath
    reverse: true
    speed: 120
    parallel: true
    maxAcceleration: 50.0
    path:
      - { x: -109, y: 19 }
      - { x: -109, y: 162, arcSpeed: 120, radius: 256 }
      - { x: -84, y: 268 }
  - { class: WaitForPath, remainingDistance: 36.0 }
  - LiftScaleHigh
  - { class: WaitForPath, remainingDistance: 1.0 }
  - WaitForHeight
  - PickerRelease
  - LiftHome

$AutoStartLeftScaleRight1Cube:
  - StartLeftPose
  - PickerHold
  - class: DrivePath
    parallel: true
    reverse: true
    speed: 100
    maxAcceleration: 70.0
    path:
      - { x: -109, y: 19 }
      - { x: -109, y: 79 }
      - { x: -109, y: 234, radius: 48 }
      - { x: 0, y: 234, speed: 70 }
      - { x: 80, y: 234, radius: 32, arcSpeed: 40, speed: 40 }
      - { x: 85.5, y: 266 }
      - { x: 85.5, y: 280 }
  - { class: WaitForPath, remainingDistance: 100.0 }
  - LiftScaleHigh
  - { class: WaitForPath, remainingDistance: 2.0 }
  - WaitForHeight
  - PickerRelease
  - LiftHome

$AutoStartRightScaleLeft1Cube:
  - StartRightPose
  - PickerHold
  - class: DrivePath
    parallel: true
    reverse: true
    speed: 100
    maxAcceleration: 70.0
    path:
      - { x: 109, y: 19 }
      - { x: 109, y: 79 }
      - { x: 109, y: 234, radius: 48 }
      - { x: 0, y: 234, speed: 70 }
      - { x: -80, y: 234, radius: 32, arcSpeed: 40, speed: 40 }
      - { x: -85.5, y: 266 }
      - { x: -85.5, y: 280 }
  - { class: WaitForPath, remainingDistance: 100.0 }
  - LiftScaleHigh
  - { class: WaitForPath, remainingDistance: 2.0 }
  - WaitForHeight
  - PickerRelease
  - LiftHome

$AutoStartRightScaleRight1Cube:
  - StartRightPose
  - { class: PickerHold, power: -0.3 }
#  - LiftSwitch
  - class: DrivePath
    reverse: true
    speed: 120
    parallel: true
    maxAcceleration: 50.0
    path:
      - { x: 109, y: 19 }
      - { x: 109, y: 162, arcSpeed: 120, radius: 256 }
      - { x: 84, y: 268 }
  - { class: WaitForPath, remainingDistance: 36.0 }
  - LiftScaleHigh
  - { class: WaitForPath, remainingDistance: 1.0 }
  - WaitForHeight
  - PickerRelease
  - LiftHome