DriveTank:
  maxAcceleration: 12.0 # units?
  leftRamper: { maxAcceleration: 12.0 }
  rightRamper: { maxAcceleration: 12.0 }
  modifiers: { deadzone: 0.1, exponent: 2.0 }
PickerPick:
  rollerPower: -0.8
  cubeDetectDistance: 200
  cubeInDistance: 50
  cubeCloseDistance: 200
  sampler: { period: .1 }
  t1: .5
  t2: .15
  t3: .55

$PickerPick:
  - PivotPick
  - { class: Wait, period: 2.0 }
  - PickerPick
  - PivotHome
$PickerPickTo45:
  - PivotPick
  - { class: Wait, period: 2.0 }
  - PickerPick
  - { class: PivotToAngle, angle: 135.0 }
PickerRelease:
  rollerPower: 1.0
  time: 1.0
PivotHome:
  { class: PivotToAngle, angle: 0.0 }
PivotPick:
  { class: PivotToAngle, angle: 180.0 }
PivotRelease:
  { class: PivotToAngle, angle: 180.0 }
LiftHome:
  { class: LiftToHeight, height: 0.0 }
LiftSwitch:
  { class: LiftToHeight, height: 24.0 }
LiftScaleLow:
  { class: LiftToHeight, height: 60.0 }
LiftScaleHigh:
  { class: LiftToHeight, height: 80.0 }