operatorInterface:
  driverJoystick: { port: 0 }
drive:
  rightMotor:
    - { type: TALON_SRX, config: { id: 9, inverted: false, feedbackDevice: CTRE_MagEncoder_Relative, limitCurrent: true, continuousCurrentLimit: 30 } }
    - { type: VICTOR_SPX, config: { id: 61, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 60, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 62, inverted: false } }
  #leftEncoder: { aChannel: 0, bChannel: 1, reverse: true, distancePerRotation: .0471238898}
  leftEncoder: { distancePerRotation: 49.152 } #not really, just compensating for code error
  leftMotor:
    - { type: TALON_SRX, config: { id: 0, inverted: false, feedbackDevice: CTRE_MagEncoder_Relative, limitCurrent: true, continuousCurrentLimit: 30 } }
    - { type: VICTOR_SPX, config: { id: 3, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 4, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 1, inverted: false } }
  #rightEncoder: { aChannel: 2, bChannel: 3, reverse: false, distancePerRotation: .0471238898}
  rightEncoder: { distancePerRotation: 49.152 , inverted: true } #not really, just compensating for code error
  rotationController:
      P: 0.05
      I: 0.0
      D: 0.0
      maxAbsoluteOutput: 0.5
  speedController:
      P: 0.015
      I: 0.0
      D: 0.0
      F: 0.0074
#      logData: true
  maxSpeed: 136
  straightMotionFollower:
      kpP: 0.1
      kiP: 0.0
      kpV: 0.0025
      kfV: .0035
      kMinOutput: .02
      kfA: 0.0004
      maxIError: 10.0
      logData: true
  yawAngleController:
      P: 0.012
      I: 0.0
      D: -0.1
      maxIError: 12.0
      logData: true
  rotationMotionFollower:
      kpP: 0.0
      kiP: 0.0
      kpV: 0.003
      kfV: 0.0014
      kMinOutput: .015
      kfA: 0.00014
      maxIError: 2.0
      logData: true
  driveSegmentsFollower:
    lookAhead: { minX: 9, minY: 9, maxX: 120, maxY: 18 }
    logData: true
    speedFollower:
      kpP: 1.5
      kiP: 0.0
      kpV: 0.0
      kfV: 1.0
      kMinOutput: 0.0
      kfA: 0.05
      maxIError: 10.0
      maxAcceleration: 100.0
      logData: true
  tankKinematics: { effectiveTrackWidth: 27.25 }
lift:
  maxHeight: 80.0
  liftMotor:
    - { type: TALON_SRX, config: { id: 58, inverted: false, feedbackDevice: CTRE_MagEncoder_Relative,
        forwardLimitSwitchSource: FeedbackConnector, reverseLimitSwitchSource: FeedbackConnector,
        forwardLimitSwitchNormal: NormallyOpen, reverseLimitSwitchNormal: NormallyOpen } }
    - { type: VICTOR_SPX, config: { id: 5, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 2, inverted: true } }
    - { type: VICTOR_SPX, config: { id: 10, inverted: true } }
  liftEncoder: { distancePerRotation: 14.127090301003344481605351170569 }
  liftController:
    kpP: 0.15
    kiP: 0.0
    kpV: 0.001
    kfV: 0.009
    kfA: 0.00089
    kMinOutput: 0.0
    kHoldPower: 0.047396935749274945
    maxOutput: 0.6
    minOutput: -0.25
    logData: true
    travelVelocity: 60.0
    maxAcceleration: 80.0
  shifter: { forwardChannel: 4, reverseChannel: 5 }
  maxBadPickHeight: 33.0
picker:
  leftRollers: { type: VICTOR_SPX, config: { id: 7, inverted: true } }
  rightRollers: { type: VICTOR_SPX, config: { id: 0, inverted: false } }
  cubeSensor: { channel: 0, type: NPN } #?
  proximitySensor: { channel: 0, distance0V: 20, distance5V: 350 } #just guessing on distance
  pickSolenoid: { channel: 1 } #pick
  releaseSolenoid: { channel: 2 } #max release
  deathGripSolenoid: { channel: 0 }
pivot:
  motor: { type: VICTOR_SPX, config: { id: 59, inverted: false } }
  position: { channel: 1, fullRange: 360, inverted: true, continuous: true, offset: -157.3, minValue: -90.0 }
  pivotPositionController:
    kComp: 0.6
    kMin: 0.6
    logData: true
