operatorInterface:
  driverJoystick: { port: 0 }
drive:
  rightMotor:
    - { type: TALON_SRX, config: { id: 9, inverted: false, feedbackDevice: CTRE_MagEncoder_Relative } }
    - { type: VICTOR_SPX, config: { id: 61, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 60, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 62, inverted: false } }
  #leftEncoder: { aChannel: 0, bChannel: 1, reverse: true, distancePerPulse: .0471238898}
  leftEncoder: { distancePerPulse: 1.0 } #todo
  leftMotor:
    - { type: TALON_SRX, config: { id: 0, inverted: false, feedbackDevice: CTRE_MagEncoder_Relative } }
    - { type: VICTOR_SPX, config: { id: 3, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 4, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 1, inverted: false } }
  #rightEncoder: { aChannel: 2, bChannel: 3, reverse: false, distancePerPulse: .0471238898}
  rightEncoder: { distancePerPulse: 1.0, inverted: true } #todo
  rotationController:
      P: 0.05
      I: 0.0
      D: 0.0
      maxAbsoluteOutput: 0.5
  speedController:
      P: 0.015
      I: 0.0
      D: 0.0
      F: .0074
#      logData: true
  maxSpeed: 136
  straightMotionFollower:
      kpP: 1.0
      kiP: 0.0
      kpV: 0.015
      kfV: .0074
      kMinOutput: .082
      kfA: 0.004
      maxIError: 10.0
#      logData: true
  yawAngleController:
      P: 0.1
      I: 0.0
      D: -0.1
      maxIError: 12.0
  #    logData: true
  rotationMotionFollower:
      kpP: 0.15
      kiP: 0.5
      kpV: 0.01
      kfV: .01
      kMinOutput: .1087
      kfA: 0.0004
      maxIError: 2.0
  #    logData: true
  driveSegmentsFollower:
    lookAhead: { minX: 9, minY: 9, maxX: 120, maxY: 18 }
    logData: true
    speedFollower:
      kpP: 2.0
      kiP: 0.0
      kpV: 0.0
      kfV: 1.0
      kMinOutput: 0.0
      kfA: 0.05
      maxIError: 10.0
      maxAcceleration: 100.0
#      logData: true
  tankKinematics: { effectiveTrackWidth: 30.0 }
#lift:
#  maxHeight: 100.0
#  changeProfileHeight: 100.0
#  liftMotor:
#    - { type: TALON_SRX, config: { id: 58, inverted: false, feedbackDevice: CTRE_MagEncoder_Relative } }
#    - { type: VICTOR_SPX, config: { id: 59, inverted: false } }
#    - { type: VICTOR_SPX, config: { id: 7, inverted: false } }
#    - { type: VICTOR_SPX, config: { id: 0, inverted: false } } # are these right? we'll find out
