defaults: [ DriveTank, LiftContinuous ]

driver:
  TRIGGER_RIGHT: toggle whenPressed $PickerPick
  TRIGGER_LEFT: toggle whenPressed $PickerRelease
  BUMPER_LEFT: start whenPressed LiftHome
  BUMPER_RIGHT: start whenPressed LiftSwitch
  POV_UP: start whenPressed PivotRelease
  POV_LEFT: start whenPressed PivotPick
  POV_DOWN: start whenPressed PivotHome
  POV_RIGHT: start whenPressed PivotTestAngle
#  START: start whenPressed $TestDrive
  B: start whenPressed $LiftScaleHighTele
  A: start whenPressed $PickerDrop
  X: start whenPressed LiftSwitch
  STICK_RIGHT: start whenPressed PivotFlip
  START: whilePressed LiftClimb
gunner:
  RIGHT_THUMB: start whenPressed LiftHome
  RIGHT_INDEX: start whenPressed LiftSwitch
  RIGHT_MIDDLE: start whenPressed $LiftScaleLowTele
  RIGHT_RING: start whenPressed $LiftScaleHighTele
  RIGHT_PINKY: start whenPressed ClimberExtendForks

  LEFT_MIDDLE:
    - start whenPressed ClimberExtendHook
    - start whenReleased ClimberRetractHook
gunnerSecondary:
  11: start whenPressed LiftForClimb
  12: start whenPressed LiftRecall