defaults: [ DriveTank ]

driver:
  #A: start whenPressed $Nothing
  B: toggle whenPressed $PickerPick
  A: toggle whenPressed PickerRelease
  X: start whenPressed LiftHome
  Y: start whenPressed LiftScaleLow
  POV_UP: start whenPressed PivotRelease
  POV_LEFT: start whenPressed PivotPick
  POV_DOWN: start whenPressed PivotHome
  POV_RIGHT: start whenPressed $PickerPickTo45